version: '3.9'

services:
  #Backend build
  api:
    build: ./Backend
    command: python3 manage.py run -h 0.0.0.0
    depends_on:
      - database
    ports:
      - 5000:5000
    env_file:
      - ./Backend/env.dev
   
    volumes:
        - .:/code



  #DB build
  database:
    
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: VacationIO
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    volumes:
      #- postgres_data:/var/lib/postgresql/data/
      - ./db-data/:/var/lib/postgresql/data=rwx/

      
